[package]
name = "temp_humidity_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"
async-std = "1.12.0"
csv = "1.2.2"